import type { Metadata } from "next";
import "./globals.css";
import { Cairo } from "next/font/google";

const cairoFont = Cairo({
  weight: ["300", "400", "600", "700", "800"],
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cairoFont.className}>{children}</body>
    </html>
  );
}
